version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  labels:
      - "dependabot"
      - "dependencies"
  ignore:
      - update-types: ["version-update:semver-patch"]
