[package]
name = "splashsurf"
version = "0.1.0"
authors = ["Fabian Löschner <loeschner@cs.rwth-aachen.de>"]
edition = "2018"

[dependencies]
splashsurf_lib = { path = "../splashsurf_lib" }
structopt = "0.3"
log = "0.4"
fern = "0.6"
chrono = "0.4"
anyhow = "1.0"
coarse-prof = "0.2"
vtkio = "0.3"
nalgebra = "0.21"
num = "0.3"
rayon = "1.3"
