name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check_format:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check format
        run: cargo fmt -- --check

  build_workspace:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  build_lib_all_features:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        run: |
          cd splashsurf_lib
          cargo build --package splashsurf_lib --all-features --verbose
      - name: Run tests
        run: |
          cd splashsurf_lib
          cargo test --package splashsurf_lib --all-features --verbose

  build_lib_no_default_features:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        run: |
          cd splashsurf_lib
          cargo build --package splashsurf_lib --no-default-features --verbose
      - name: Run tests
        run: |
          cd splashsurf_lib
          cargo test --package splashsurf_lib --no-default-features --verbose
